### ISSUE TITLE
Scaffold generation

### ISSUE THREAD

**Issue by albertma-evotec** [undeadpixel/reinvent-scaffold-decorator#1]
Hi, 
For the Method - Sampling process - Scaffold model section in the paper, you mentioned 10M scaffold were sampled from a scaffold generator model. Is this model provided anywhere? Because as far as I understand the model I trained (following the instruction using my own data) is a decorator model which decorate given scaffold(s). I could not see any model that generate **scaffolds**. 
Please correct me if I misunderstand.
Thanks
Albert

**Comment by undeadpixel** [comment]
Hi Albert,

I have not uploaded the actual trained models for the scaffolds because they are quite easily trained models that can be easily replicated. The model architecture I used for the scaffolds is the usual seq2seq RNN. It is already published in https://github.com/undeadpixel/reinvent-randomized . I just added the training sets to the repository too (in the training_sets folder). You can use any other molecular generative architecture, too, although especially with the DRD2, randomized SMILES would be advisable due to the training set size.

Hope it helps, and reopen the issue if you have any additional issue/question!

Bye!

Josep
